spring:
  main:
    web-application-type: none
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: backup-scheduler
backup:
  host: 10.211.55.17:8088
  db: thingworx
  rp: autogen
restore:
  host: localhost:8088
  db: thingworx
  rp: autogen
  path: /opt/homebrew/opt/influxdb@1/bin
  backup-directory: /Users/dolee/IdeaProjects
